export enum RealtimeEventType {
  HOLYRICS_CONNECTED = 'HOLYRICS_CONNECTED',
  HOLYRICS_DISCONNECTED = 'HOLYRICS_DISCONNECTED',
  BIBLE_CHANGED = 'BIBLE_CHANGED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  TRANSCRIPTION_RECEIVED = 'TRANSCRIPTION_RECEIVED',
  COMMAND_IDENTIFIED = 'COMMAND_IDENTIFIED',
  COMMAND_EXECUTED = 'COMMAND_EXECUTED',
  SPEECH_STARTED = 'SPEECH_STARTED',
  SPEECH_STOPPED = 'SPEECH_STOPPED',
  SONG_CHANGED = 'SONG_CHANGED',
}
