export enum CommandType {
  BIBLE_REFERENCE = 'BIBLE_REFERENCE',
  NEXT_VERSE = 'NEXT_VERSE',
  PREVIOUS_VERSE = 'PREVIOUS_VERSE',
  NEXT_CHAPTER = 'NEXT_CHAPTER',
  PREVIOUS_CHAPTER = 'PREVIOUS_CHAPTER',
  UNKNOWN = 'UNKNOWN',
}
